apiVersion: v1
kind: Service
metadata:
  name: gotify
  namespace: gotify
  labels:
    app: gotify
spec:
  type: LoadBalancer
  selector:
    app: gotify
  ports:
    - name: http
      port: 8090
      targetPort: 80
      protocol: TCP

