apiVersion: v1
kind: Service
metadata:
  name: temporal
  namespace: temporal
spec:
  selector:
    app: temporal
  type: LoadBalancer
  ports:
    - name: frontend
      port: 7233
      targetPort: 7233

---
apiVersion: v1
kind: Service
metadata:
  name: temporal-web
  namespace: temporal
spec:
  selector:
    app: temporal-web
  type: LoadBalancer
  ports:
    - name: http
      port: 7234
      targetPort: 8080

