apiVersion: v1
kind: Service
metadata:
  name: belugabot
  namespace: belugabot
  labels:
    app: belugabot
spec:
  type: LoadBalancer
  selector:
    app: belugabot
  ports:
    - name: http
      port: 18792
      targetPort: 18792
      protocol: TCP
