apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - cerbos
  - cloudflare
  - kafka
  - kestra
  - mongodb
  - mysql
  - nats
  - postgres
  - redis
  - temporal
