apiVersion: v1
kind: Service
metadata:
  name: makemkv-drive1
  namespace: makemkv
spec:
  type: LoadBalancer
  selector:
    app: makemkv
    statefulset.kubernetes.io/pod-name: makemkv-0
  ports:
    - name: web
      port: 5801
      protocol: TCP
      targetPort: 5800
---
apiVersion: v1
kind: Service
metadata:
  name: makemkv-drive2
  namespace: makemkv
spec:
  type: LoadBalancer
  selector:
    app: makemkv
    statefulset.kubernetes.io/pod-name: makemkv-1
  ports:
    - name: web
      port: 5802
      protocol: TCP
      targetPort: 5800
---
apiVersion: v1
kind: Service
metadata:
  name: makemkv-drive3
  namespace: makemkv
spec:
  type: LoadBalancer
  selector:
    app: makemkv
    statefulset.kubernetes.io/pod-name: makemkv-2
  ports:
    - name: web
      port: 5803
      protocol: TCP
      targetPort: 5800
---
apiVersion: v1
kind: Service
metadata:
  name: makemkv-drive4
  namespace: makemkv
spec:
  type: LoadBalancer
  selector:
    app: makemkv
    statefulset.kubernetes.io/pod-name: makemkv-3
  ports:
    - name: web
      port: 5804
      protocol: TCP
      targetPort: 5800

