apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - seraex-secret.yaml
  - ../../../secrets/ghcr-secret.yaml
patches:
  - patch: |
      - op: replace
        path: /metadata/namespace
        value: seraex
      - op: replace
        path: /metadata/name
        value: ghcr-secret
    target:
      kind: Secret
      name: ghcr
