apiVersion: v1
kind: Secret
metadata:
    name: tautulli-config
    namespace: tautulli
type: Opaque
stringData:
    PLEX_URL: ENC[AES256_GCM,data:7/6z4PvreolyehpllTarHLZ2NkNKomd7xwDQnvHQSBiK8kqGzKBikA==,iv:Ye4I9jKnZl6CBrHxBz9ORIKGmC3jnDpiSBTZzDBKDXQ=,tag:+JN0Cq/Ya8t7WD1f8+8i1Q==,type:str]
    PLEX_TOKEN: ENC[AES256_GCM,data:HDWkKZbUxWLO8yquvLQ/gUIHhg==,iv:PutIMx38cZVwNcnQSDnh74Xd/OfeGfU+Up5qV3tzKng=,tag:UCYgDxLz+u7lF8H//5hbLg==,type:str]
sops:
    age:
        - recipient: age1yubikey1q2u7ajmktdc5e5ejq98qmrwha8xglt06k96zupqmh6e6qzfvh434s0wa5yy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IHpDZE9kUSBBaFVKR09Q
            WFpOd08zS215K2NKR21pdEw2aERDNWJ2Zlowa1NZM0xScFhhTQpseXQ3T0pDcTIv
            d0lTOGE3aXEvQUVRRm04L1BmT2VGdE55SHl3VjRaRFVZCi0tLSA0QU01czZaSGh6
            QTBwblk0MGZtZlg2ZGt4bEJ4Wm1Ud2QxNXpQdFIzbnQ0CoPfeDYy9RjpqDLQhEL0
            WwMjv0ALFZILSrLxyQp4UFnIL2QnLUIQZDiZY3rPTr81xMVancqC2tyM48/L899w
            ahE=
            -----END AGE ENCRYPTED FILE-----
        - recipient: age140jklplcfmptcv2q0jek2uee0aga2c2zd9c5p8jw5c8kyg9sef0sqwkh9k
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZTllMnlWdzdoWTdXc2ho
            SFBzMUVMKzJTdXhHY3BYU1FDTlhSMitMTlFBCm9PU2RQK1lHUHJ0U21QSnhWVmly
            eUFCVkRwZUpVaS8zbnhqNElsOUxSSk0KLS0tIFlmbDhwQmtEYWR3Ym1TamJWNllX
            S1o0SEpTdzY0UnRZditsbWpYSExpUEEKRny/5s0o0ZdwjhfrX1WyZzOL/6Tu+/N3
            1PRM45Qawnqt8yEMt/K8bLyKHEGrR6A1+XoXdrbLN1opd8zZ4KONGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T23:08:23Z"
    mac: ENC[AES256_GCM,data:t7jqkbNSbzlb1HIuWkdoJNxrgrt2hjlGIk7Vvhwr91bXiSGUjHiS/gJ2S+qSdZsMatxm2rb0vNP8X3egw4Uo0OJp1iKWg3Hg5XRHor5ZVwFw82g7cvQmD49UIhv8e79X6dH9SogIElAcP4boP8AhzTytCUBCI5eW46c7s9gyCLc=,iv:Thfsmd6aLqX/hZo5IQ+zEki2iC/KctQI7nA0brzZ15o=,tag:ECJg485DlnIR6Z1S5ZPjjQ==,type:str]
    encrypted_regex: ^(data|stringData|email|dnsZones)$
    version: 3.11.0
