apiVersion: v1
kind: Service
metadata:
  name: sera
  namespace: sera
  labels:
    app: sera
spec:
  type: ClusterIP
  selector:
    app: sera
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
