apiVersion: v1
kind: Service
metadata:
  name: seraui
  namespace: seraui
  labels:
    app: seraui
spec:
  type: ClusterIP
  selector:
    app: seraui
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
