apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflare-config
  namespace: cloudflare
data:
  config.yaml: |
    # Tunnel configuration - Routes are managed via Cloudflare Dashboard
    tunnel: 414c90a2-c38a-46b2-9d6b-53670c4dfc3f
    metrics: 0.0.0.0:2000
    no-autoupdate: true